version: 2.1

jobs:
# Exercise: Config and Deployment
    configure_infrastructure: 
      docker:
        - image: python:3.7-alpine3.11
      steps:
        - checkout
        - add_ssh_keys:
            # You can get this ID in the section where you registered the SSH Key
            fingerprints: ["2f:69:22:a9:2b:ea:33:db:0e:63:40:e7:90:d3:c8:79"] 
        - run:
            name: Install Ansible
            command: |
              apk add --update ansible
        - run:
            name: Run Playbook and Configure server
            command: |
              ansible-playbook -i inventiry main.yml
              

    # Exercise: Smoke Testing
    smoke_test:
      docker:
       - image: alpine:latest
      steps:
        - run: apk add --update curl
        - run:
           name: smoke test
           command: |
             URL="https://blog.udacity.com/"
             # Test if website exists
             if curl -s --head ${URL} 
             then
               return 0
             else
               return 1
             fi


workflows:

  myWorkflow:
    jobs:
      - configure_infrastructure
      - smoke_test
