version: 2.1

jobs:
  create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
               aws cloudformation deploy \
                   --template-file stacks.yml \
                    --stack-name myStack-udacity \
                    --region us-east-1

workflows:

  myWorkflow:
    jobs:
      - create_infrastructure
